### PR TITLE
AVIF, JPEG2000 and JXL improvements

### PR DESCRIPTION
**Pull request by novomesk**
Hello Marcus,
this is work in progress, do not approve yet.
I need AppVeyor build to test/verify changes on Windows.

### CODE REVIEW

**Comment by novomesk** [comment]
@diemmarkus 
These commits should solve https://github.com/nomacs/nomacs/issues/557 , https://github.com/nomacs/nomacs/issues/554 and partially https://github.com/nomacs/nomacs/issues/562

I haven't changed DkSaveDialog.cpp I want to ask you what is better to do (or not to do there). JPEG2000 should save with transparency so I think in case of `j2k_dialog`, the background color selector (`mColChooser`) should be probably hidden. Do you want to have it that way or you wish to have various background colors for demonstration purposes?

Regarding the [JPEG XL](https://www.youtube.com/watch?v=t63DBrQCUWc) support I have the https://github.com/novomesk/qt-jpegxl-image-plugin . It works on Linux, but for Windows I have to wait till VisualStudio issues are solved in [libjxl](https://gitlab.com/wg1/jpeg-xl/).

**Comment by BlueSwordM** [comment]
So, you've probably seen it already, but we're at JXL 0.2 RC, which means the bitstream is frozen.

Like you've said last time, I think it is the time.

**Comment by BlueSwordM** [comment]
Anyway, I just want to wish you good holidays!

**Comment by novomesk** [comment]
@BlueSwordM  
Hello Zak,
I do not have success to build the library on Windows because of some `hwy/ops/scalar-inl.h:700:24: error: call to 'signbit' is ambiguous`
jxl_win
Nomacs for Windows is built using MS tools.
Do you know where is the problem?

**Comment by BlueSwordM** [comment]
I do not know actually.
I'd like to help, but I never compile stuff on Windows.
I'll ask for some of my Windows dev friends to see what perhaps the issue is.

In the meantime, how would I actually compile with the JXL plugin? I know how to do it with AVIF, but not JXL because there's no CMakefile for it.

**Comment by 1480c1** [comment]
Seems that the line 700 will require explicitly casting from.raw to one of the options of float, double, or long double

**Comment by novomesk** [comment]
> In the meantime, how would I actually compile nomacs with the JXL plugin?

The Qt plug-in [qt-jpegxl-image-plugin](https://github.com/novomesk/qt-jpegxl-image-plugin) is independent to nomacs. Once installed, all Qt based applications can use the new format.
These are the steps how to build it and install it:
```
qmake qt-jpegxl-image-plugin.pro
make
make install
```

**Comment by G2G2G2G** [comment]
Did you remove the bundling of the dll from the installer?

**Comment by novomesk** [comment]
@G2G2G2G 
The installers with the JXL plug-in were built successfully:
https://ci.appveyor.com/project/diemmarkus/nomacs/builds/40251225/artifacts

But I had to edit the build script somehow because AppVeyor machine got upgraded and the old script stopped working.

**Pull request merged**
