### PR TITLE
Merged compile instructions into README and added section for OSX

### PR DESCRIPTION
**Pull request by martinm82**
This is just a proposal to merge the separate instruction files into one README. I have extended also the installation instruction for OSX. At least I could compile as described on OSX El Capitan.

Modified also a bit the Windows instructions since the description was not up-to-date anymore (exiv2-0.23 does not exist in the source tree). Once I setup Windows on my Mac I will try to verify the instructions.

### CODE REVIEW

**Comment by diemmarkus** [comment]
hi,
thanks a lot! - The thing is, that I recently merged the instructions to the README.md too (but in the developer branch - which is the nomacs 3.0 branch see https://github.com/nomacs/nomacs/tree/developer). Would it be possible for you to add your updates/comments there? -> this request has conflicts which should not be the case in the developer

**Comment by martinm82** [comment]
Hi,
sure, I will try to apply them on the developer branch instead.

**Comment by diemmarkus** [comment]
cool. thanks!

**Comment by diemmarkus** [comment]
I have now added this manually... thanks!

**Pull request closed without merging**
