### PR TITLE
fixed #569 Build fails with quazip 1.0

### LINKED ISSUE #569: Build fails with quazip 1.0
**Describe the bug**
When building nomacs 3.16.224 using quazip 1.0 the cmake configuration phase fails.

**To Reproduce**
1. Install quazip 1.0
2. Run cmake
```
/usr/bin/cmake /home/abuild/rpmbuild/BUILD/nomacs-3.16.224/ImageLounge/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/nomacs -DCMAKE_BUILD_TYPE=Release '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fno-strict-aliasing' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fno-strict-aliasing' -DUSE_SYSTEM_QUAZIP=ON -DCMAKE_SHARED_LINKER_FLAGS= -DENABLE_TRANSLATIONS=ON
```
3. See error
```
-- Checking for module 'quazip'
--   Package 'quazip', required by 'virtual:world', not found
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (QUAZIP)
  does not match the name of the calling package (QuaZip5).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
 Call Stack (most recent call first):
  cmake/FindQuaZip5.cmake:41 (find_package_handle_standard_args)
  cmake/Unix.cmake:107 (find_package)
  CMakeLists.txt:122 (include)
```

**Expected behavior**
Expecting quazip to be detected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [openSUSE Tumbleweed]
 - Version [current]

**Additional context**
Quazip has now a -Qt(5|6) suffix and it comes with config scripts.

### PR DESCRIPTION
**Pull request by pvanek**
it addresses https://github.com/nomacs/nomacs/issues/569

### CODE REVIEW

**Comment by uthidata** [comment]
This works on my machine. Can you branch the package on the OBS while the official package is not updated yet?

**Comment by pvanek** [comment]
@uthidata well, it's already there since beginning. See:

https://build.opensuse.org/package/show/graphics/nomacs

with the patch for cmake handling

The package in `graphics` project is the source for all factories and updates

**Comment by uthidata** [comment]
oh thank you, I didn't notice. Been wondering why nomacs is not installing for weeks now, but I see that the fix was accepted into factory 4 days ago.

**Comment by diemmarkus** [comment]
Thanks Petr!

**Pull request merged**
