### PR TITLE
Include a git version tag, if built from a git repo.

### PR DESCRIPTION
**Pull request by derlunz**
- makes `nomacs --version` report:

   [INFO] Hi there
   Image Lounge 3.7 (git: 3.6.1-48-g3494189-dirty)

- About dialog shows the same string.

### CODE REVIEW

**Comment by agaida** [comment]
Nice, but it would be nice to have a way to put in a version from a kind of version file  - rationale: yes, i do git builds and the git version would be nice to have - but i don't build  directly from git.

The workflow is:
* get current sources
* mention it in changelog
* build a source package
* upload it to the builder

The reason for doing so - i don't build things local, only in clean build environments - most distributions do this to be sure that the receipe will work and no dependency is missed in the receipe. But it would be a big help to have the git version string for these builds too.

**Comment by derlunz** [comment]
The git version tag is optional. It will only be appended, if building from a git repo. So the PR should meet the requirements right now. This is just a minimal implementation.


You want a version file? No problem. I'd could implement a scheme akin to the one found in [opencv](https://github.com/opencv/opencv/blob/master/cmake/OpenCVVersion.cmake):

- have a version file e.g. `${CMAKE_SOURCE_DIR}/src/DkCore/version.h`, that defines  the current version:
```
...
#define NOMACS_VERSION_MAJOR    3
#define NOMACS_VERSION_MINOR    1
#define NOMACS_VERSION_REVISION 0
#define NOMACS_VERSION_STATUS   "-dev"
...
```
- have `cmake`parse that file, and set set corresponding variables within the build system, possibly append a git tag.
- have `cmake` generate a final version file `${CMAKE_BUILD_DIR}/version.h` :
```
...
#define NOMACS_VERSION_MAJOR    3
#define NOMACS_VERSION_MINOR    1
#define NOMACS_VERSION_REVISION 0
#define NOMACS_VERSION_STATUS   "-dev"
#define NOMACS_VERSION_VCSTAG   "<A_NICE_GIT_TAG_OR_EMPTY>"
#define NOMACS_FULL_VERSION "3.1.0-dev <A_NICE_GIT_TAG>"
...
```
or
```
...
#define NOMACS_VERSION_MAJOR    3
#define NOMACS_VERSION_MINOR    1
#define NOMACS_VERSION_REVISION 0
#define NOMACS_VERSION_STATUS   "-dev"
#define NOMACS_VERSION_VCSTAG   ""
#define NOMACS_FULL_VERSION "3.1.0-dev"
...
```
- include the generated `${CMAKE_BUILD_DIR}/version.h` within application code.

That way we get:
 - version is set in dedicated header file
- version information is used by the build system
- the git tag is only appended when building from a git repo.

Concerning the build work flow:

>    get current sources

```
     git pull origin/master
```
>    mention it in changelog
```    
$EDIT ImageLounge/src/changelog.txt
git commit -am 'updated change log for release X.Y'
```
>    build a source package
``` 
build and check for goodness
```

>    upload it to the builder
```
git tag 'X.Y.Z' 
git push --tags origin/master
```
How do you cause the builder to start? Doesn't it use git to retrieve the sources?

**Comment by derlunz** [comment]
I just saw what you meant. It seems, you use the travis builder. In that case you want to pass a tag description via environment variable to cmake. Something like:

```yml
#filename: .travis.yml
...
before-script:
  - NOMACS_CI_TAG=`git describe --tags --always $TRAVIS_COMMIT`
  - CMAKE_ARGS+=" -DNOMACS_BUILD_TAG=$NOMACS_CI_TAG"
...
```
NOTE: This is just conceptual. I haven't ever touched a travis file.

**Comment by agaida** [comment]
nop, you misunderstand - i upload a source build to my repo - and thats all. The same way i would upload a source build to debian or ubuntu or a ppa on launchpad. And no - i would never use git to get the sources in the builder.

**Comment by derlunz** [comment]
So that means no git tag in a binary for debs. Considering the patches applied during packaging that doesn't make sense anyway. Other question: 

Does it make sense, resp. is there a way to brand the binaries as coming from some distro?
Why can you work with a "version file" and not with an environmental variable? Why not patching the build script?

**Comment by agaida** [comment]
Thats easy - why should one patch sources if there is a way to simply read a file or may be an option? There might be several ways to provide some informations. Environmental variables may be one way, something like options are another way. I should have a look at, should be an one or two-liner to achieve that. Sorry for the late answer, was busy that weekend, building my first Arm-System.

**Comment by derlunz** [comment]
Take your time, the source tree will be still be there. Thanks for looking into it.

**Comment by diemmarkus** [comment]
I'll close this request - since there are no recent updates...

**Pull request closed without merging**
