### PR TITLE
macOS: Fix missing libs warning

### PR DESCRIPTION
**Pull request by hmueller01**
see #1172 

Does not fix `ld: warning: ignoring duplicate libraries: '-lc++'` in all the plugins ...
ATM only for `libnomacsCore-3.19.1.dylib` and `nomacs.app/Contents/MacOS/nomacs`

### CODE REVIEW

**Comment by scrubbbbs** [comment]
I'm thinking it is probably not a great idea to drop the warning, it must exist for a reason, and I don't understand what that reason is. Even though in this case (-lc++) it is innocuous, I'm wondering if this could result in future issues or mask problems that require our attention.

Also, there is another proposed solution in the issue you linked in #1172 which does not involve disabling the warning (reinstalling gcc was suggested).

**Comment by hmueller01** [comment]
It just ignores double -l options. And if you write `gcc -lc++ -lc++ ...` who cares. This warning is useless.
Of course I tried the reinstalling of gcc but it didn't help in my case. But if you do not like the solution I'll remove this part of the PR.

**Comment by scrubbbbs** [comment]
> This warning is useless

Maybe, maybe not. At least it can change the link order of the binary which can cause subtle changes. Since nomacs uses a shared library which is also linked to plugins, we need to pay extra attention to link warnings.

I'd like to remove it, thanks!

**Comment by hmueller01** [comment]
Ok, fair enough. Removed that.

**Pull request merged**
