### PR TITLE
Fix macos bundle

### PR DESCRIPTION
**Pull request by hmueller01**
Fixed a few things to make build work on macOS.

### CODE REVIEW

**Comment by novomesk** [comment]
Hello @s-daveb ,

You tried to build nomacs on MacOS in the past.
Would you like to test these changes and tell me if you agree with them.

**Comment by s-daveb** [comment]
The first `make` call failed unless I ran `export CPLUS_INCLUDE_PATH=/usr/local/include` before `make`, but the second call to `make bundle` failed with:

```
[100%] Linking CXX executable nomacs.app/Contents/MacOS/nomacs
[100%] Built target nomacs
build ❯ make bundle                                                                              master
CMake Error at bundle.cmake:17 (file):
  file COPY cannot find "/Resources/qt_menu.nib": No such file or directory.
```

**Comment by hmueller01** [comment]
The first point is documented in the `README.md`. I hope you've seen this.

The second failure this is really strange. Did you really checkout this branch?
`make bundle` shouldn't use `bundle.cmake` at all, as I replaced this target by macdeployqt
```
get_target_property(_qmake_executable Qt5::qmake IMPORTED_LOCATION)
get_filename_component(_qt_bin_dir "${_qmake_executable}" DIRECTORY)
find_program(MACDEPLOYQT_EXECUTABLE macdeployqt HINTS "${_qt_bin_dir}")

add_custom_target(bundle
	COMMAND ${MACDEPLOYQT_EXECUTABLE} ${BINARY_NAME}.app -dmg
	DEPENDS ${BINARY_NAME}
	COMMENT "Execute ${MACDEPLOYQT_EXECUTABLE} to create macOS bundle")
```
at the end of `MacBuildTarget.cmake`.

The whole command should look like this (if nomacs.app and nomacs.dmg are not yet created):
```
> make bundle
[  1%] Automatic MOC for target nomacsCore-3.17.0
[  1%] Built target nomacsCore-3.17.0_autogen
[ 60%] Built target nomacsCore-3.17.0
[ 61%] Automatic MOC for target nomacs
[ 61%] Built target nomacs_autogen
[ 98%] Built target nomacs
[100%] Execute /usr/local/opt/qt5/bin/macdeployqt to create macOS bundle
[100%] Built target bundle
```

**Comment by scrubbbbs** [comment]
@hmueller01 the latest commit 0491de2e4e0fea421c449bb14e260db7d155329b compiles and runs with Qt 6, but the bundle is still broken. Would you be able to rebase and test with Qt6?

**Comment by hmueller01** [comment]
MacBuildTarget.cmake is completely hardcoded for Qt5. 
e.g. `target_link_libraries(${BINARY_NAME} Qt5::Widgets Qt5::Gui Qt5::Network Qt5::PrintSupport Qt5::Concurrent Qt5::Svg)`
Is it ok to drop Qt5 or should both be supported?

**Comment by scrubbbbs** [comment]
Qt6 port is still incomplete so we would need both. There are no references to Qt5 in UnixBuildTarget.cmake nor the current version of MacBuildTarget.cmake so it shouldn't be necessary to drop one or the other, just substitute Qt:: for Qt5:: and the version will be selectable with `cmake -D QT_VERSION_MAJOR=[5|6]`

If there is a conflict, you can do a conditional on QT_VERSION_MAJOR (see MingwBuildTarget) for how its done.

**Comment by hmueller01** [comment]
Unfortunately my fork was broken and I was not able to repair it. I'll close this PR and open a new one based on the latest master.

**Comment by hmueller01** [comment]
closed by #1143

**Pull request closed without merging**
