### PR TITLE
Drif image format

### PR DESCRIPTION
**Pull request by ovidiuvio**
Please check the following before submitting a *pull request*:

- Fork [nomacs](https://github.com/nomacs/nomacs.git) and create your branch from `master`
- Pull requests are only accepted if they pass [travis](https://travis-ci.org/nomacs/nomacs)

also have a look at our [CONTRIBUTING.md](https://github.com/nomacs/nomacs/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by diemmarkus** [comment]
cool, thanks!
do you also have a test image?

**Comment by ovidiuvio** [comment]
Hi,

Please find bellow a google drive link with those images.
https://drive.google.com/uc?id=1-QMEAyulVfRZ2wR1nfdHpWHjQzjJT3Hw&export=download

Those were obtained from the following jpgs:

p6220437
p8180558



The process to obtain one is:
Convert  a jpg image with ffmpeg to one of the yuv / rgb formats supported by drif loader.
Append a footer with drif info to the end of the file.

I have some scripts / sample code for that as well, but it is more of a quick hack to obtain them.

[DrifUtil.zip](https://github.com/nomacs/nomacs/files/2486563/DrifUtil.zip)



Regards,
Ovidiu

**Comment by diemmarkus** [comment]
thank you, works fine! I fixed two linux/os x issues, now it compiles on all officially supported systems...
- are there any plans to add metadata?

**Comment by ovidiuvio** [comment]
Hi,

There is some space reserved in the footer for that, but for now, there are no plans to add metadata.
The format is designed to be an as simple as possible container for raw image data.

Regards,
Ovidiu

**Pull request merged**
