### PR TITLE
Fix runtimepath on linux

### PR DESCRIPTION
**Pull request by derlunz**
This PR should fix issue #109

### CODE REVIEW

**Comment by agaida** [comment]
Cool, impressive - works like charm. :)

**Comment by derlunz** [comment]
Thanks! Most of the work was already there.

BTW, if you stumble over packaging issues, just contact me. I am running Nomacs under Linux myself, so I am in a good position to give feedback on that platform.

**Comment by agaida** [comment]
than we are at least two who use nomacs with linux - and i  maintain the debian packages

**Comment by diemmarkus** [comment]
I guess that's good to merge than : )

**Comment by agaida** [comment]
ok, your latest changes created a little bit havoc in the packaging - thats cleaner now. with the patch applied we can deliver nomacs as one binary with private libs included. That will ease the packaging pain a lot.

**Pull request merged**
