### PR TITLE
Features/travis ci

### PR DESCRIPTION
**Pull request by martinm82**
Created travis ci configuration for Linux and OSX builds. 

Next steps:
* Build for Windows
* Deploying artifacts to bintray or github releases
* Creating own homebrew package for OSX

### CODE REVIEW

**Comment by diemmarkus** [comment]
thank you!

**Comment by martinm82** [comment]
BTW, could you signup at https://travis-ci.org with you nomacs account. Right now only my fork is tested on Travis but it would be good to do it on the official rep.

**Comment by diemmarkus** [comment]
we are working on it: https://travis-ci.org/nomacs/nomacs : )

**Comment by martinm82** [comment]
Argh, sorry :)

**Comment by diemmarkus** [comment]
np - actually @sfiel tried it a few weeks ago... now we are all set there (thanks to your yml). Linux (developer branch) is working fine - but the OS X seems to have issues with the find_package of Qt5.
thanks again!

**Comment by sfiel** [comment]
hi,
we have now fixed the Os x problems  ... thanks for your initial travis file, your next steps sound for travis sound also very interessting. we don't know currently what travis is capable to do for us :)

**Comment by martinm82** [comment]
Sorry, I was this week completely busy with my job. I am also quite new to travis but reading the documentation it looks like it has a lot to offer. Unfortunately there is no Windows support available :( But I will have a look at the release part and create a proposal as soon as I have more time.

**Pull request merged**
